export const translation = [
  {
    English: 'Select Login type',
    Gujarati: 'પ્રવેશ પ્રકાર પસંદ કરો',
    Hindi: 'लॉगिन प्रकार का चयन करें',
    Punjabi: 'ਲੌਗਇਨ ਕਿਸਮ ਚੁਣੋ',
    Tamil: 'உள்நுழைவு வகையைத் தேர்ந்தெடுக்கவும்',
    Urdu: 'لاگ ان کی قسم منتخب کریں۔',
  },
  {
    English: 'Admin Login',
    Gujarati: 'વહીવટકર્તા પ્રવેશ',
    Hindi: 'व्यवस्थापक लॉगिन',
    Punjabi: 'ਪ੍ਰਬੰਧਕ ਲਾਗਇਨ',
    Tamil: 'நிர்வாகி உள்நுழைவு',
    Urdu: 'ایڈمن لاگ ان',
  },
  {
    English: 'User Login',
    Gujarati: 'વપરાશકર્તા પ્રવેશ',
    Hindi: 'उपयोगकर्ता लॉगिन',
    Punjabi: 'ਉਪਭੋਗਤਾ ਲੌਗਇਨ',
    Tamil: 'பயனர் உள்நுழைவு',
    Urdu: 'صارف لاگ ان',
  },
  {
    English: 'Login',
    Gujarati: 'પ્રવેશ કરો',
    Hindi: 'लॉग इन करें',
    Punjabi: 'ਲਾਗਿਨ',
    Tamil: 'உள்நுழைய',
    Urdu: 'لاگ ان کریں',
  },
  {
    English: 'Create New Account',
    Gujarati: 'નવું એકાઉન્ટ બનાવો',
    Hindi: 'नया खाता बनाएँ',
    Punjabi: 'ਨਵਾਂ ਖਾਤਾ ਬਣਾਓ',
    Tamil: 'புதிய கணக்கை உருவாக்க',
    Urdu: 'نیا اکاؤنٹ بنانے',
  },
  {
    English: 'Select Language',
    Gujarati: 'ભાષા પસંદ કરો',
    Hindi: 'भाषा चुने',
    Punjabi: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    Tamil: 'மொழியை தேர்ந்தெடுங்கள்',
    Urdu: 'زبان منتخب کریں',
  },
];
